# Generated by Django 2.0.1 on 2018-03-24 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstInningss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('current_over', models.IntegerField(default=0)),
                ('openers_selected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('overs', models.IntegerField(default=0)),
                ('match_status', models.IntegerField(default=0)),
                ('toss_winner_choice', models.CharField(default='Select', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MatchAdditional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_innings', models.CharField(blank=True, max_length=10, null=True)),
                ('toss_stored', models.BooleanField(default=False)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings', models.CharField(max_length=11)),
                ('ball_number', models.IntegerField(blank=True, null=True)),
                ('over_number', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('wicket', models.BooleanField(default=False)),
                ('six', models.BooleanField(default=False)),
                ('four', models.BooleanField(default=False)),
                ('is_highlight', models.BooleanField(default=False)),
                ('highlight', models.CharField(blank=True, max_length=20, null=True)),
                ('batsman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='batsman', to='player.Player')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_1_score', models.BigIntegerField(default=0)),
                ('team_2_score', models.BigIntegerField(default=0)),
                ('team_2_wickets', models.IntegerField(default=0)),
                ('team_1_wickets', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SecondInnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('current_over', models.IntegerField(default=0)),
                ('openers_selected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('owner', models.CharField(max_length=20)),
                ('logo', models.ImageField(upload_to='')),
                ('players', models.ManyToManyField(to='player.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('place', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(default=None)),
                ('tournament_status', models.IntegerField(default=0)),
                ('tournament_schedule', models.IntegerField(default=0)),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizer.Organizer')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament'),
        ),
        migrations.AddField(
            model_name='secondinnings',
            name='batting_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='batting_team2', to='tournament.Team'),
        ),
        migrations.AddField(
            model_name='secondinnings',
            name='bowling_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bowling_team2', to='tournament.Team'),
        ),
        migrations.AddField(
            model_name='secondinnings',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Match'),
        ),
        migrations.AddField(
            model_name='secondinnings',
            name='non_striker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='non_striker2', to='player.Player'),
        ),
        migrations.AddField(
            model_name='secondinnings',
            name='striker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='striker2', to='player.Player'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='winner', to='tournament.Team'),
        ),
        migrations.AddField(
            model_name='score',
            name='batting_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='batting_team', to='tournament.Team'),
        ),
        migrations.AddField(
            model_name='score',
            name='bowler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bowler', to='player.Player'),
        ),
        migrations.AddField(
            model_name='score',
            name='bowling_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bowling_team', to='tournament.Team'),
        ),
        migrations.AddField(
            model_name='score',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Match'),
        ),
        migrations.AddField(
            model_name='score',
            name='out_batsman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='out_batsman', to='player.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_1', to='tournament.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_2', to='tournament.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='toss_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='toss_winner', to='tournament.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament'),
        ),
        migrations.AddField(
            model_name='firstinningss',
            name='batting_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='batting_team1', to='tournament.Team'),
        ),
        migrations.AddField(
            model_name='firstinningss',
            name='bowling_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bowling_team1', to='tournament.Team'),
        ),
        migrations.AddField(
            model_name='firstinningss',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Match'),
        ),
        migrations.AddField(
            model_name='firstinningss',
            name='non_striker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='non_strike1', to='player.Player'),
        ),
        migrations.AddField(
            model_name='firstinningss',
            name='striker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='striker1', to='player.Player'),
        ),
    ]
