# Generated by Django 2.0.2 on 2018-02-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('owner', models.CharField(max_length=20)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
    ]
