# Generated by Django 2.0.1 on 2018-03-25 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20180324_1844'),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstinningss',
            name='current_bowler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_bowler1', to='player.Player'),
        ),
        migrations.AddField(
            model_name='secondinnings',
            name='current_bowler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_bowler2', to='player.Player'),
        ),
    ]
