# Generated by Django 2.0.2 on 2018-02-21 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20180219_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overs', models.IntegerField()),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_1', to='tournament.Team')),
                ('team_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_2', to='tournament.Team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='winner', to='tournament.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_number', models.IntegerField()),
                ('over_number', models.IntegerField()),
                ('run', models.IntegerField()),
                ('extra_run', models.IntegerField()),
                ('is_wicket', models.BooleanField(default=False)),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='batting_team', to='tournament.Team')),
                ('bowling_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bowling_team', to='tournament.Team')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Match')),
            ],
        ),
    ]
