# Generated by Django 2.0.2 on 2018-02-21 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_organizer'),
        ('tournament', '0003_match_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organizer.Organizer'),
            preserve_default=False,
        ),
    ]
