# Generated by Django 2.0.2 on 2018-02-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_tournament_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='score',
            name='extra_type',
            field=models.CharField(choices=[('Wide', 'Wide'), ('NoBall', 'NoBall'), ('DeadBall', 'DeadBall')], default=None, max_length=11),
        ),
        migrations.AddField(
            model_name='score',
            name='innings',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second')], default=None, max_length=11),
        ),
        migrations.AddField(
            model_name='score',
            name='wicket_type',
            field=models.CharField(choices=[('RunOut', 'RunOut'), ('Catch', 'Catch'), ('Bowled', 'Bowled'), ('Lbw', 'Lbw'), ('Stumps', 'Stumps'), ('HitWicket', 'HitWicket')], default=None, max_length=11),
        ),
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
