# Generated by Django 2.0.2 on 2018-03-04 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_auto_20180223_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='batting_team',
        ),
        migrations.RemoveField(
            model_name='score',
            name='bowling_team',
        ),
        migrations.RemoveField(
            model_name='score',
            name='match',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='status',
        ),
        migrations.AlterField(
            model_name='match',
            name='team_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tournament.Team'),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
