# Generated by Django 2.0.1 on 2018-04-10 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_auto_20180327_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match_winner', to='tournament.Team'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='image',
            field=models.ImageField(blank=True, default='tournaments/no.png', upload_to='tournaments'),
        ),
    ]
