# Generated by Django 2.0.2 on 2018-03-04 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_auto_20180304_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='status',
        ),
    ]
