# Generated by Django 2.0.2 on 2018-03-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_remove_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
