# Generated by Django 2.0.2 on 2018-03-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_auto_20180305_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='wicket_type',
            field=models.CharField(choices=[('RunOut', 'RunOut'), ('Catch', 'Catch'), ('Bowled', 'Bowled'), ('Lbw', 'Lbw'), ('Stumps', 'Stumps'), ('HitWicket', 'HitWicket')], max_length=11),
        ),
    ]
