# Generated by Django 2.0.2 on 2018-03-06 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_auto_20180305_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='status',
        ),
    ]
