# Generated by Django 2.0.3 on 2018-03-08 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_auto_20180306_1835'),
        ('tournament', '0015_remove_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='batsman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='batsman', to='player.Player'),
        ),
        migrations.AddField(
            model_name='score',
            name='bowler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bowler', to='player.Player'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='extra_run',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='extra_type',
            field=models.CharField(blank=True, choices=[('Wide', 'Wide'), ('NoBall', 'NoBall'), ('DeadBall', 'DeadBall')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='wicket_type',
            field=models.CharField(blank=True, choices=[('RunOut', 'RunOut'), ('Catch', 'Catch'), ('Bowled', 'Bowled'), ('Lbw', 'Lbw'), ('Stumps', 'Stumps'), ('HitWicket', 'HitWicket')], max_length=11, null=True),
        ),
    ]
