# Generated by Django 2.0.1 on 2018-03-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0016_auto_20180308_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_schedule',
            field=models.BooleanField(default=0),
        ),
    ]
