# Generated by Django 2.0.1 on 2018-03-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0017_tournament_tournament_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_schedule',
            field=models.IntegerField(default=0),
        ),
    ]
