# Generated by Django 2.0.3 on 2018-03-11 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0006_auto_20180311_2114'),
        ('player', '0010_remove_player_team'),
        ('tournament', '0019_match_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Match')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player1', to='player.Player'),
        ),
        migrations.AddField(
            model_name='team',
            name='player10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player10', to='player.Player'),
        ),
        migrations.AddField(
            model_name='team',
            name='player11',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player11', to='player.Player'),
        ),
        migrations.AddField(
            model_name='team',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player2', to='player.Player'),
        ),
        migrations.AddField(
            model_name='team',
            name='player3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player3', to='player.Player'),
        ),
        migrations.AddField(
            model_name='team',
            name='player4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player4', to='player.Player'),
        ),
        migrations.AddField(
            model_name='team',
            name='player5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player5', to='player.Player'),
        ),
        migrations.AddField(
            model_name='team',
            name='player6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player6', to='player.Player'),
        ),
        migrations.AddField(
            model_name='team',
            name='player7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player7', to='player.Player'),
        ),
        migrations.AddField(
            model_name='team',
            name='player8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player8', to='player.Player'),
        ),
        migrations.AddField(
            model_name='team',
            name='player9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player9', to='player.Player'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='team_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team1', to='tournament.Team'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='team_1_player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_1_player1', to='performance.PerformanceMatchWise'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='team_1_player10',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_1_player10', to='performance.PerformanceMatchWise'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='team_1_player11',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_1_player11', to='performance.PerformanceMatchWise'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='team_1_player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_1_player2', to='performance.PerformanceMatchWise'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='team_1_player3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_1_player3', to='performance.PerformanceMatchWise'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='team_1_player4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_1_player4', to='performance.PerformanceMatchWise'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='team_1_player5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_1_player5', to='performance.PerformanceMatchWise'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='team_1_player6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_1_player6', to='performance.PerformanceMatchWise'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='team_1_player7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_1_player7', to='performance.PerformanceMatchWise'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='team_1_player8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_1_player8', to='performance.PerformanceMatchWise'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='team_1_player9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_1_player9', to='performance.PerformanceMatchWise'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='team_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team2', to='tournament.Team'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='team_2_player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_2_player1', to='performance.PerformanceMatchWise'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='team_2_player10',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_2_player10', to='performance.PerformanceMatchWise'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='team_2_player11',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_2_player11', to='performance.PerformanceMatchWise'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='team_2_player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_2_player2', to='performance.PerformanceMatchWise'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='team_2_player3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_2_player3', to='performance.PerformanceMatchWise'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='team_2_player4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_2_player4', to='performance.PerformanceMatchWise'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='team_2_player5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_2_player5', to='performance.PerformanceMatchWise'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='team_2_player6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_2_player6', to='performance.PerformanceMatchWise'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='team_2_player7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_2_player7', to='performance.PerformanceMatchWise'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='team_2_player8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_2_player8', to='performance.PerformanceMatchWise'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='team_2_player9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_2_player9', to='performance.PerformanceMatchWise'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament'),
        ),
    ]
