# Generated by Django 2.0.3 on 2018-03-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0006_auto_20180311_2114'),
        ('tournament', '0022_auto_20180311_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorecard',
            name='team_1_player1',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='team_1_player10',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='team_1_player11',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='team_1_player2',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='team_1_player3',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='team_1_player4',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='team_1_player5',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='team_1_player6',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='team_1_player7',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='team_1_player8',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='team_1_player9',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='team_2_player1',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='team_2_player10',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='team_2_player11',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='team_2_player2',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='team_2_player3',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='team_2_player4',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='team_2_player5',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='team_2_player6',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='team_2_player7',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='team_2_player8',
        ),
        migrations.RemoveField(
            model_name='scorecard',
            name='team_2_player9',
        ),
        migrations.AddField(
            model_name='scorecard',
            name='team_1_players',
            field=models.ManyToManyField(related_name='team_1_players', to='performance.PerformanceMatchWise'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='team_2_players',
            field=models.ManyToManyField(related_name='team_2_players', to='performance.PerformanceMatchWise'),
        ),
    ]
