# Generated by Django 2.0.3 on 2018-03-12 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0023_auto_20180311_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='toss_winner',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='toss_winner', to='tournament.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='toss_winner_choice',
            field=models.CharField(choices=[('Batting', 'Batting'), ('Bowling', 'Bowling')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
