# Generated by Django 2.0.3 on 2018-03-12 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0024_auto_20180312_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='toss_winner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='toss_winner', to='tournament.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='toss_winner_choice',
            field=models.CharField(max_length=10),
        ),
    ]
