# Generated by Django 2.0.3 on 2018-03-12 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0026_auto_20180312_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='toss_winner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='toss_winner', to='tournament.Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='toss_winner_choice',
            field=models.CharField(default='Select', max_length=10),
        ),
    ]
