# Generated by Django 2.0.3 on 2018-03-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0027_auto_20180312_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='toss_winner_choice',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
