# Generated by Django 2.0.3 on 2018-03-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0033_match_toss_stored'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
