# Generated by Django 2.0.3 on 2018-03-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0035_remove_scorecard_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
