# Generated by Django 2.0.3 on 2018-03-12 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0037_auto_20180312_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='team_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team1', to='tournament.Team'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='team_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team2', to='tournament.Team'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament'),
        ),
    ]
