# Generated by Django 2.0.3 on 2018-03-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0038_auto_20180312_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team_1_score',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team_1_wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team_2_score',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team_2_wickets',
            field=models.IntegerField(default=0),
        ),
    ]
