# Generated by Django 2.0.1 on 2018-03-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0039_auto_20180312_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='extra_run',
        ),
        migrations.RemoveField(
            model_name='score',
            name='extra_type',
        ),
        migrations.RemoveField(
            model_name='score',
            name='is_wicket',
        ),
        migrations.RemoveField(
            model_name='score',
            name='run',
        ),
        migrations.RemoveField(
            model_name='score',
            name='wicket_type',
        ),
        migrations.AddField(
            model_name='score',
            name='description',
            field=models.CharField(default='Hello', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='innings',
            field=models.CharField(max_length=11),
        ),
    ]
