# Generated by Django 2.0.1 on 2018-03-15 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0041_match_openers_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='openers_selected',
        ),
    ]
