# Generated by Django 2.0.1 on 2018-03-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0042_remove_match_openers_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='openers_selected_innings1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='openers_selected_innings2',
            field=models.BooleanField(default=False),
        ),
    ]
