# Generated by Django 2.0.1 on 2018-03-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0043_auto_20180315_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='openers_selected',
            field=models.BooleanField(default=False),
        ),
    ]
