# Generated by Django 2.0.1 on 2018-03-15 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0045_auto_20180315_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='non_striker_innings1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='non_striker_innings1', to='performance.PerformanceMatchWise'),
        ),
        migrations.AlterField(
            model_name='match',
            name='non_striker_innings2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='non_striker_innings2', to='performance.PerformanceMatchWise'),
        ),
        migrations.AlterField(
            model_name='match',
            name='striker_innings1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='striker_innings1', to='performance.PerformanceMatchWise'),
        ),
        migrations.AlterField(
            model_name='match',
            name='striker_innings2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='striker_innings2', to='performance.PerformanceMatchWise'),
        ),
    ]
