# Generated by Django 2.0.1 on 2018-03-15 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0046_auto_20180315_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='non_striker_innings1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='non_striker_innings1', to='performance.PerformanceMatch'),
        ),
        migrations.AlterField(
            model_name='match',
            name='non_striker_innings2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='non_striker_innings2', to='performance.PerformanceMatch'),
        ),
        migrations.AlterField(
            model_name='match',
            name='striker_innings1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='striker_innings1', to='performance.PerformanceMatch'),
        ),
        migrations.AlterField(
            model_name='match',
            name='striker_innings2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='striker_innings2', to='performance.PerformanceMatch'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='team_1_players',
            field=models.ManyToManyField(related_name='team_1_players', to='performance.PerformanceMatch'),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='team_2_players',
            field=models.ManyToManyField(related_name='team_2_players', to='performance.PerformanceMatch'),
        ),
    ]
