# Generated by Django 2.0.1 on 2018-03-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0010_remove_player_team'),
        ('tournament', '0047_auto_20180315_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='four',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='score',
            name='highlight',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='is_highlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='score',
            name='out_batsman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='out_batsman', to='player.Player'),
        ),
        migrations.AddField(
            model_name='score',
            name='six',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='score',
            name='wicket',
            field=models.BooleanField(default=False),
        ),
    ]
