# Generated by Django 2.0.1 on 2018-03-16 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0048_auto_20180316_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='ball_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='batting_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='batting_team', to='tournament.Team'),
        ),
        migrations.AlterField(
            model_name='score',
            name='bowling_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bowling_team', to='tournament.Team'),
        ),
        migrations.AlterField(
            model_name='score',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Match'),
        ),
        migrations.AlterField(
            model_name='score',
            name='over_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
