# Generated by Django 2.0.1 on 2018-03-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0049_auto_20180316_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='current_over',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='overs',
            field=models.IntegerField(default=0),
        ),
    ]
