# Generated by Django 2.0.3 on 2018-03-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20180324_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
