# Generated by Django 2.0.3 on 2018-03-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_player_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, upload_to='players/'),
        ),
    ]
