# Generated by Django 2.0.3 on 2018-03-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20180327_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='image_description',
        ),
    ]
