# Generated by Django 2.0.2 on 2018-02-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20180219_2106'),
        ('player', '0004_auto_20180219_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ManyToManyField(null=True, to='tournament.Team'),
        ),
    ]
