# Generated by Django 2.0.2 on 2018-03-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_auto_20180220_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ManyToManyField(to='tournament.Team'),
        ),
    ]
