# Generated by Django 2.0.3 on 2018-03-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_auto_20180327_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.FileField(blank=True, upload_to='players'),
        ),
    ]
