# Generated by Django 2.0.2 on 2018-03-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_auto_20180305_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ManyToManyField(null=True, to='tournament.Team'),
        ),
    ]
