# Generated by Django 2.0.3 on 2018-03-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_auto_20180327_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
