# Generated by Django 2.0.3 on 2018-03-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_auto_20180306_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
    ]
