# Generated by Django 2.0.2 on 2018-03-06 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0009_auto_20180306_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMatchWise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('batting_runs', models.BigIntegerField()),
                ('strike_rate', models.FloatField()),
                ('sixes', models.IntegerField()),
                ('fours', models.IntegerField()),
                ('bowling_runs', models.BigIntegerField()),
                ('wickets', models.BigIntegerField()),
                ('bowling_avg', models.FloatField()),
                ('economy', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournaments', models.BigIntegerField()),
                ('matches', models.BigIntegerField()),
                ('batting_innings', models.BigIntegerField()),
                ('batting_runs', models.BigIntegerField()),
                ('high_score', models.BigIntegerField()),
                ('batting_avg', models.FloatField()),
                ('batting_best', models.BigIntegerField()),
                ('strike_rate', models.FloatField()),
                ('hundreds', models.BigIntegerField()),
                ('fifties', models.BigIntegerField()),
                ('sixes', models.IntegerField()),
                ('fours', models.IntegerField()),
                ('bowling_runs', models.BigIntegerField()),
                ('bowling_innings', models.BigIntegerField()),
                ('wickets', models.BigIntegerField()),
                ('bowling_avg', models.FloatField()),
                ('bowling_best', models.FloatField()),
                ('economy', models.FloatField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
            ],
        ),
        migrations.AddField(
            model_name='performancematchwise',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.PerformanceTotal'),
        ),
    ]
