# Generated by Django 2.0.1 on 2018-03-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BattingInnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batting_runs', models.BigIntegerField(default=0)),
                ('strike_rate', models.FloatField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('batting_balls', models.BigIntegerField(default=0)),
                ('status', models.CharField(max_length=20)),
                ('out', models.BooleanField(default=False)),
                ('out_type', models.CharField(max_length=20)),
                ('played', models.BooleanField(default=False)),
                ('started_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BowlingInnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bowling_runs', models.BigIntegerField(default=0)),
                ('batting_balls', models.BigIntegerField(default=0)),
                ('bowling_overs', models.BigIntegerField(default=0)),
                ('wickets', models.BigIntegerField(default=0)),
                ('bowling_avg', models.FloatField(default=0)),
                ('economy', models.FloatField(default=0)),
                ('played', models.BooleanField(default=False)),
                ('started_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournaments', models.BigIntegerField(default=0)),
                ('matches', models.BigIntegerField(default=0)),
                ('batting_innings', models.BigIntegerField(default=0)),
                ('batting_runs', models.BigIntegerField(default=0)),
                ('batting_balls', models.BigIntegerField(default=0)),
                ('high_score', models.BigIntegerField(default=0)),
                ('batting_avg', models.FloatField(default=0)),
                ('batting_best', models.BigIntegerField(default=0)),
                ('strike_rate', models.FloatField(default=0)),
                ('hundreds', models.BigIntegerField(default=0)),
                ('fifties', models.BigIntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('bowling_runs', models.BigIntegerField(default=0)),
                ('bowling_innings', models.BigIntegerField(default=0)),
                ('wickets', models.BigIntegerField(default=0)),
                ('bowling_avg', models.FloatField(default=0)),
                ('bowling_best', models.FloatField(default=0)),
                ('economy', models.FloatField(default=0)),
            ],
        ),
    ]
