# Generated by Django 2.0.2 on 2018-03-06 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_auto_20180306_1835'),
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancematchwise',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='player.Player'),
            preserve_default=False,
        ),
    ]
