# Generated by Django 2.0.2 on 2018-03-06 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_performancematchwise_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancematchwise',
            name='performance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='performance.PerformanceTotal'),
        ),
    ]
