# Generated by Django 2.0.3 on 2018-03-07 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015_remove_match_status'),
        ('performance', '0003_auto_20180306_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancematchwise',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match', to='tournament.Match'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performancematchwise',
            name='performance',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='performance.PerformanceTotal'),
            preserve_default=False,
        ),
    ]
