# Generated by Django 2.0.3 on 2018-03-07 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_auto_20180307_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancematchwise',
            name='match',
        ),
    ]
