# Generated by Django 2.0.3 on 2018-03-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0005_remove_performancematchwise_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancematchwise',
            name='performance',
        ),
        migrations.AddField(
            model_name='performancematchwise',
            name='bowling_overs',
            field=models.BigIntegerField(default=4),
            preserve_default=False,
        ),
    ]
