# Generated by Django 2.0.3 on 2018-03-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0006_auto_20180311_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancematchwise',
            name='bowling_avg',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='performancematchwise',
            name='bowling_overs',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='performancematchwise',
            name='bowling_runs',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='performancematchwise',
            name='economy',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='performancematchwise',
            name='fours',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='performancematchwise',
            name='sixes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='performancematchwise',
            name='strike_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='performancematchwise',
            name='wickets',
            field=models.BigIntegerField(null=True),
        ),
    ]
