# Generated by Django 2.0.3 on 2018-03-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0007_auto_20180311_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancematchwise',
            name='batting_runs',
            field=models.BigIntegerField(null=True),
        ),
    ]
