# Generated by Django 2.0.3 on 2018-03-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0008_auto_20180312_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancematchwise',
            name='batting_runs',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performancematchwise',
            name='bowling_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='performancematchwise',
            name='bowling_overs',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performancematchwise',
            name='bowling_runs',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performancematchwise',
            name='economy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='performancematchwise',
            name='fours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performancematchwise',
            name='sixes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performancematchwise',
            name='strike_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='performancematchwise',
            name='wickets',
            field=models.BigIntegerField(default=0),
        ),
    ]
