# Generated by Django 2.0.3 on 2018-03-12 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0009_auto_20180312_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancematchwise',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='player.Player'),
        ),
    ]
