# Generated by Django 2.0.3 on 2018-03-12 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0034_scorecard_status'),
        ('performance', '0011_auto_20180312_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancematchwise',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Team'),
        ),
    ]
