# Generated by Django 2.0.3 on 2018-03-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0012_performancematchwise_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancematchwise',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
