# Generated by Django 2.0.3 on 2018-03-12 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0013_performancematchwise_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancetotal',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='player.Player'),
        ),
    ]
