# Generated by Django 2.0.3 on 2018-03-12 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0038_auto_20180312_1824'),
        ('performance', '0014_auto_20180312_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancematchwise',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament'),
        ),
    ]
