# Generated by Django 2.0.3 on 2018-03-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0015_performancematchwise_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancetotal',
            name='batting_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='performancetotal',
            name='batting_best',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performancetotal',
            name='batting_innings',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performancetotal',
            name='batting_runs',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performancetotal',
            name='bowling_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='performancetotal',
            name='bowling_best',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='performancetotal',
            name='bowling_innings',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performancetotal',
            name='bowling_runs',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performancetotal',
            name='economy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='performancetotal',
            name='fifties',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performancetotal',
            name='fours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performancetotal',
            name='high_score',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performancetotal',
            name='hundreds',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performancetotal',
            name='matches',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performancetotal',
            name='sixes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performancetotal',
            name='strike_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='performancetotal',
            name='tournaments',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performancetotal',
            name='wickets',
            field=models.BigIntegerField(default=0),
        ),
    ]
