# Generated by Django 2.0.3 on 2018-03-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0017_performancematchwise_batting_balls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancematchwise',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
