# Generated by Django 2.0.3 on 2018-03-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0018_auto_20180312_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancetotal',
            name='batting_balls',
            field=models.BigIntegerField(default=0),
        ),
    ]
