# Generated by Django 2.0.3 on 2018-03-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0019_performancetotal_batting_balls'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancematchwise',
            name='out',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='performancematchwise',
            name='out_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancematchwise',
            name='played',
            field=models.BooleanField(default=0),
        ),
    ]
