# Generated by Django 2.0.1 on 2018-03-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0010_remove_player_team'),
        ('performance', '0020_auto_20180313_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancematchwise',
            name='wickets_players',
            field=models.ManyToManyField(related_name='wicket_players', to='player.Player'),
        ),
    ]
