# Generated by Django 2.0.1 on 2018-03-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0021_performancematchwise_wickets_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancematchwise',
            name='bowling_balls',
            field=models.IntegerField(default=0),
        ),
    ]
