# Generated by Django 2.0.1 on 2018-03-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0023_remove_performancematchwise_bowling_balls'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancematchwise',
            name='started_time',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
