# Generated by Django 2.0.1 on 2018-03-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0024_performancematchwise_started_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancematchwise',
            name='started_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
