# Generated by Django 2.0.1 on 2018-03-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0025_auto_20180315_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancematchwise',
            name='started_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
