# Generated by Django 2.0.1 on 2018-03-14 18:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0026_auto_20180315_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancematchwise',
            name='started_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 18, 44, 57, 701063, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
