# Generated by Django 2.0.1 on 2018-03-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0027_auto_20180315_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancematchwise',
            name='started_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
