# Generated by Django 2.0.1 on 2018-03-14 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0028_auto_20180315_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancematchwise',
            name='started_time',
        ),
    ]
