# Generated by Django 2.0.1 on 2018-03-15 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0046_auto_20180315_1414'),
        ('player', '0010_remove_player_team'),
        ('performance', '0030_performancematchwise_started_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattingInnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batting_runs', models.BigIntegerField(default=0)),
                ('strike_rate', models.FloatField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('batting_balls', models.BigIntegerField(default=0)),
                ('status', models.CharField(max_length=20)),
                ('out', models.BooleanField(default=False)),
                ('out_type', models.CharField(max_length=20)),
                ('played', models.BooleanField(default=False)),
                ('started_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BowlingInnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bowling_runs', models.BigIntegerField(default=0)),
                ('batting_balls', models.BigIntegerField(default=0)),
                ('bowling_overs', models.BigIntegerField(default=0)),
                ('wickets', models.BigIntegerField(default=0)),
                ('bowling_avg', models.FloatField(default=0)),
                ('economy', models.FloatField(default=0)),
                ('status', models.CharField(max_length=20)),
                ('played', models.BooleanField(default=False)),
                ('started_time', models.DateTimeField(blank=True, null=True)),
                ('wickets_players', models.ManyToManyField(to='player.Player')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.BooleanField(default=False)),
                ('batting_innings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batting_innings', to='performance.BattingInnings')),
                ('bowling_innings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bowling_innings', to='performance.BowlingInnings')),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Match')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='player.Player')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Team')),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament')),
            ],
        ),
    ]
