# Generated by Django 2.0.1 on 2018-03-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0033_auto_20180315_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancematch',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
