# Generated by Django 2.0.1 on 2018-03-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0034_auto_20180315_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancematch',
            name='status',
        ),
    ]
