# Generated by Django 2.0.2 on 2018-02-18 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='dob',
        ),
    ]
