# Generated by Django 2.0.2 on 2018-02-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('organizer', '0002_remove_organizer_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Organizer',
        ),
    ]
